version: 0.2
env:
  variables:
    AWS_ACCOUNT_ID: "265556570017"
    CLUSTER: "prueba-pipeline"
    SERVICE: "back-prueba"
    IMAGE_REPO_NAME: "prueba-pipe"
    IMAGE_TAG: "latest"
    AWS_DEFAULT_REGION: "us-west-2"

phases:
  install:
    runtime-versions:
      commands:
      - sudo apt update
      - apt install -y software-properties-common curl
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get install -y nodejs

  pre_build:
    commands:
      - echo Logueo AWS ECR....
      - eval $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo Build Docker image
      - npm install
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG .
      - echo COpiando Imagen de Docker al repo....
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
